org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

org.gradle.configuration-cache=false

mod_version=1.15.0
maven_group=dev.santora
archives_base_name=santora

loom_version=1.17.14

loader_version=0.19.3

# 1.21.x uses Java 21.
minecraft_version_121=1.21
minecraft_range_121=>=1.21 <1.21.2
minecraft_label_121=1.21
fabric_api_version_121=0.102.0+1.21

minecraft_version_1212=1.21.5
minecraft_range_1212=>=1.21.2 <1.21.6
minecraft_label_1212=1.21.2
fabric_api_version_1212=0.128.2+1.21.5

minecraft_version_1216=1.21.6
minecraft_range_1216=>=1.21.6 <1.21.9
minecraft_label_1216=1.21.6
fabric_api_version_1216=0.128.2+1.21.6

minecraft_version_1219=1.21.9
minecraft_range_1219=>=1.21.9 <1.21.11
minecraft_label_1219=1.21.9
fabric_api_version_1219=0.134.1+1.21.9

minecraft_version_1211=1.21.11
minecraft_range_1211=1.21.11
minecraft_label_1211=1.21.11
fabric_api_version_1211=0.141.5+1.21.11

java_version_121x=21

# The 26.1.x uses Java 25.
minecraft_version_261=26.1.2
minecraft_range_261=>=26.1 <26.2
minecraft_label_261=26.1
fabric_api_version_261=0.155.2+26.1.2
java_version_261=25

# 26.2 uses Java 25.
minecraft_version_262=26.2
fabric_api_version_262=0.155.0+26.2
java_version_262=25
