pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'santora'

include 'core'
include 'v1_21'
include 'v1_21_2'
include 'v1_21_6'
include 'v1_21_9'
include 'v1_21_11'
include 'v26_1'
include 'v26_2'
