pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'santora'

include 'core'

['v1_21', 'v1_21_2', 'v1_21_6', 'v1_21_9', 'v1_21_11', 'v26_1', 'v26_2'].each {
	include it
	project(":${it}").projectDir = file("targets/${it}")
}
