plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

ext {
	mcVersion = minecraft_version_1219
	mcRange = minecraft_range_1219
	mcLabel = minecraft_label_1219
	fabricApi = fabric_api_version_1219
	extraTrees = ['sharedResourceLocation', 'sharedInputEvent', 'sharedGuiGraphics', 'sharedMusicGain']
}

apply from: rootProject.file('gradle/mc121.gradle')
