plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
}

ext {
	mcVersion = minecraft_version_121
	mcRange = minecraft_range_121
	mcLabel = minecraft_label_121
	fabricApi = fabric_api_version_121
	extraTrees = ['sharedResourceLocation', 'sharedInputLegacy', 'sharedGuiGraphics', 'sharedMusicGain']
}

apply from: rootProject.file('gradle/mc121.gradle')
